# @package _global_
defaults:
  - trainer: default.yaml
  - datamodule: data.yaml
  - models: evaluate.yaml
  - logger: wandb.yaml
  - hydra: default.yaml
  - _self_

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: ${models.max_epochs}
  devices: 1
  accelerator: 'gpu'

work_dir: ${hydra:runtime.cwd}
data_dir: ${data_loc}
log_dir: ${work_dir}/${log_loc}

# path to folder with data
data_loc: "/home/milad/CHILS/data"
log_loc: logs

# Additional hyperparams
seed: 42
source_dataset: "food-101"
arch: "ClipViTL14"
pretrained: True
base_task: "food-101"
num_classes: 1000

